# Generated by Django 3.0.3 on 2020-05-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
    ]
